### PR TITLE
Add JavaScript Question

### PR DESCRIPTION
**Pull request by kairules55**
Added JavaScript Interview question.
What are javascript promises?

### CODE REVIEW

**Comment by arpansac** [comment]
You need to resolve the conflicts! Please take a fresh pull of the development branch from upstream, merge it with your branch and re create the PR, before anyone else does )

**Comment by arpansac** [comment]
Please resolve the conflicts!

**Comment by shivamyth** [comment]
Any update. Take a fresh pull and update the PR otherwise, the PR will get deleted in the next 24 hrs.

**Review by shivamyth — COMMENTED** [review]
Take a fresh pull and remove the conflicts. Update it otherwise the PR will get close in next 24 hrs.

**Comment by shivamyth** [comment]
You haven't updated the PR, closing it for now

**Pull request closed without merging**
