### PR TITLE
Newq js question7

### PR DESCRIPTION
**Pull request by priyanka-kagrahari**
Added question 7 and the answer

### CODE REVIEW

**Review by shivamyth — CHANGES_REQUESTED** [review]
Take a fresh pull and update the PR. You are creating Javascript Question on html/index.html. Correct it

**Review by arpansac — CHANGES_REQUESTED** [review]
You changed the wrong file! instead of html/index.html, it should be javascript/index.html

**Comment by priyanka-kagrahari** [comment]
Updated the correct javascript/index.html file and removed the reference from html/index.html file.

**Comment by priyanka-kagrahari** [comment]
Updated the correct file javascript/index.html and removed the reference from html/index.html.

**Comment by priyanka-kagrahari** [comment]
Closing this PR. Will be creating a new PR for the changes.

**Pull request closed without merging**
