### PR TITLE
Newq css ques

### PR DESCRIPTION
**Pull request by 23ashutosh3**

### CODE REVIEW

**Review by shivamyth — CHANGES_REQUESTED** [review]
There are unnecessary changes in the PR, you have changed unnecessarily files. Take a fresh Pull and update the PR.

**Comment by 23ashutosh3** [comment]
Ohh 😴
Okk

**Comment by dakshkhetan** [comment]
@23ashutosh3 Any updates on this? This PR will be closed in 24 hours if no changes are made.

**Comment by shivamyth** [comment]
No updates on the PR, closing it for now.

**Pull request closed without merging**
