### PR TITLE
Newq js34 interview

### PR DESCRIPTION
**Pull request by 23ashutosh3**
pls check

### CODE REVIEW

**Review by dakshkhetan — CHANGES_REQUESTED** [review]
@23ashutosh3 Please take a fresh pull (from upstream development) and then commit your changes.

**Comment by 23ashutosh3** [comment]
Sir for fresh pull request ,I have to run this line on cmd
Git remote add upstream https://github.com/CodingNinjasCodes/InterQues.git
???

**Comment by dakshkhetan** [comment]
@23ashutosh3  Yes, after adding upstream, run command `git pull upstream development`
Please do the changes ASAP.

**Comment by dakshkhetan** [comment]
No changes are done. Closing this PR.

**Pull request closed without merging**
