### PR TITLE
Hotfix sample

### PR DESCRIPTION
**Pull request by 23ashutosh3**
Javascript Quistion

### CODE REVIEW

**Review by dakshkhetan — COMMENTED** [review]
@23ashutosh3 What are the changes you've committed in this PR?

**Comment by dakshkhetan** [comment]
Closing this PR due to no response.

**Comment by 23ashutosh3** [comment]
Sir I added new javascript quistion in javascript folder

**Comment by dakshkhetan** [comment]
But it shows no file changed.
You can do one thing, start the contribution process from the beginning.
Clone the repo again, and create branch  named, 'newq-[your-name]'.
And after adding question, raise a new PR.

**Comment by 23ashutosh3** [comment]
Ok

**Pull request closed without merging**
