### PR TITLE
added question and answer number 47 in javascript section

### PR DESCRIPTION
**Pull request by astrivedi007**

### CODE REVIEW

**Review by dakshkhetan — CHANGES_REQUESTED** [review]
Hey @astrivedi007, please add an image or screenshot (for reference) for each type of popup, else everything looks good to me. :)

**Comment by astrivedi007** [comment]
ok sure sir

**Review by dakshkhetan — APPROVED** [review]
LGTM. 👍🏻

**Comment by astrivedi007** [comment]
thanks a lot.

**Pull request merged**
